### ISSUE TITLE
Reporobot possibly not checking for itself as a collaborator

### ISSUE THREAD

**Issue by mdouglasbrett** [jlord/reporobot#28] opened 2015-05-11 16:16 UTC
Hi jlord. 

I'm a big fan of git-it/nodeschool. I recently passed its_a_small_world, but I managed to pass it with the wrong collaborator (I had typoed and put Reprobot as a collaborator instead - https://github.com/ReproBot). I removed Reprobot and ran the verifier again by mistake (I'm not the slickest in terminal), this time without any collaborator on my patchwork repo, yet still passed. 

I noticed that in reprobot/collaborate.js, we are checking `permissions.push` against the username supplied by its_a_small_world/verify.js:

```
 var repo = github.getRepo(username, 'patchwork')
 var collab = false

 repo.show(function(err, repo) {
 if (err) return callback(err)

var permissions = repo.permissions
if (permissions.push) {
  collab = true
  callback(null, collab)
} else {
  collab = false
  callback(null, collab)
}
})
```

Is it possible that the username from its_a_small_world/verify.js:

```
exec('git config user.username', function(err, stdout, stdrr) {
var username = stdout.trim()
collaborating(username)
})
```

will always result in `collab = true`, as the repo we are checking is a fork (and therefore I assume I have full permissions)?

If this is the case, then it might be hard to catch if you have made a mistake when completing the exercise. If you are a bit of a crappy typist (like me), you will not trigger reporobot's confirmation email, but still pass and possibly give somebody else push permission to your repo (and maybe end up a git pull away from being totally pwned :scream:). 

Is there a way we can check for `repo.collaborators` instead? I do not know enough about the output of `git.show` to tell.

Anyway, sorry about the lengthy message - let me know if I'm barking up the wrong tree.

All the best, 

Mike :)

**Comment by jlord** [comment] 2017-01-29 21:22
Hey!

> will always result in collab = true, as the repo we are checking is a fork (and therefore I assume I have full permissions)?

It is not checking to see if _you_, `username`, have permission to your fork, but if @reporobot does. 

When @reporobot makes the request to check if it has permissions, it does so by [authorizing itself with the GitHub API](https://github.com/jlord/reporobot/blob/master/collabcheck.js#L13). So it should be checking the right permissions.

If I test the endpoint Git-it uses with the @eviljlord account, which has a fork of `jlord/patchwork` but with no collaborators:

`http://reporobot.jlord.us/collab?username=eviljlord`

I get:

```text
{
  "collab": false
}
```

If I try with my account @jlord, which has a fork with @reporobot as a collaborator.

`http://reporobot.jlord.us/collab?username=jlord`

I get:

```text
{
  "collab": true
}
```

So I'm not sure why you were able to see it as passing. Just to be clear, you were using the terminal version of Git-it? (`jlord/git-it`) and not the new desktop app one (`jlord/git-it-electron`)?

**Comment by jlord** [comment] 2017-01-29 21:23
Oh wow, I just noticed the date on this issue—you likely have long forgotten about this! Since I can't reproduce it, I'm going to close this for now and wait and see if it happens to anyone else. Thanks!

**Closed by jlord** 2017-01-29 21:23 UTC
